// Passive slot-choice logging: every "go to work" step in a plan can record where
// the droid landed, so normal play produces the data instead of test evenings.
const fs=require('fs');
const APP='c:/Users/admin/OneDrive/Desktop/Droid Tycoon Helper/app.js';
let s=fs.readFileSync(APP,'utf8');
const NL='\r\n', J=a=>a.join(NL);
const sub=(from,to)=>{const n=s.split(from).length-1;if(n!==1){console.error('MATCHED '+n+'x:\n'+from.slice(0,170));process.exit(1)}s=s.split(from).join(to)};

// ── the store ───────────────────────────────────────────────────────────────
sub("// ─── Slot Lab ─",J([
"// ─── Slot choice log ────────────────────────────────────────────────────────",
"// One row per observed placement: where the droid started, which slots were free",
"// at that moment, and which one the game gave it. Kept in its own localStorage",
"// key rather than in the profile — it is research data, it can get long, and",
"// putting it in the profile would mean touching export, import, validate and the",
"// cloud schema, any of which could lose a Base. Export from the Slot Lab instead.",
"const SLOT_LOG_KEY='droid-archive-slot-log';",
"const slotLogAll=()=>{try{const rows=JSON.parse(localStorage.getItem(SLOT_LOG_KEY)||'[]');return Array.isArray(rows)?rows:[]}catch(e){return[]}};",
"const slotLogWrite=rows=>{try{localStorage.setItem(SLOT_LOG_KEY,JSON.stringify(rows.slice(-4000)))}catch(e){}};",
"const slotLogClear=()=>slotLogWrite([]);",
"const slotLogTracking=()=>{try{return localStorage.getItem('droid-archive-slot-track')==='1'}catch(e){return false}};",
"const slotLogSetTracking=on=>{try{localStorage.setItem('droid-archive-slot-track',on?'1':'0')}catch(e){}};",
"// Which slots of a station are free right now, ignoring any this plan has already",
"// filled — those are gone by the time the next droid is sent.",
"function slotLogFree(station,taken){",
"  const occupied=new Set(placements().placed.filter(x=>x.station===station).map(x=>x.slot));",
"  for(const slot of taken||[])occupied.add(slot);",
"  return stationSlotIndices(station).filter(slot=>!occupied.has(slot));",
"}",
"function slotLogAdd(row){",
"  if(!Number.isInteger(row.landed)||!row.station)return false;",
"  // A landing outside the free set means the Base is out of date, and a wrong row",
"  // is worse than no row.",
"  if(!row.free.includes(row.landed))return false;",
"  const rows=slotLogAll();",
"  rows.push({...row,at:new Date().toISOString(),rebirth:state.rebirth});",
"  slotLogWrite(rows);",
"  return true;",
"}",
"",
"// ─── Scoring the rules against the log ──────────────────────────────────────",
"// Each rule guesses the landing from the origin and the free set. Whichever",
"// predicts the log best is the one Optimise should be using.",
"const SLOT_RULES_UNDER_TEST=[",
"  {id:'nearest',name:'Nearest free slot to where it started',",
"   pick:row=>slotLogNearest(row.station,row.free,row.fromStation,row.fromSlot)},",
"  {id:'mission',name:'Mission slots first, then nearest',",
"   pick:row=>{",
"     if(row.station==='ASTROMECH'){",
"       const mission=row.free.filter(slot=>ASTROMECH_MISSION_SLOTS.includes(slot));",
"       if(mission.length)return slotLogNearest(row.station,mission,row.fromStation,row.fromSlot);",
"     }",
"     return slotLogNearest(row.station,row.free,row.fromStation,row.fromSlot);",
"   }},",
"  {id:'fixed',name:'The fixed order the app ships with',",
"   pick:row=>slotFillOrder(row.station).find(slot=>row.free.includes(slot))},",
"  {id:'lowest',name:'Lowest free slot number',pick:row=>Math.min(...row.free)},",
"];",
"// Distance between two slots on the map. Both floors are drawn on one image, so",
"// changing floor gets a flat penalty rather than real geometry.",
"const SLOT_FLOOR_PENALTY=12;",
"function slotLogPoint(station,slot){",
"  for(const floor of MAP_FLOORS){",
"    const spots=MAP_SPOTS[floor]||{};",
"    const lists=station==='LOUNGE'?[spots.LOUNGE,spots.LOUNGE_REBIRTH,spots.LOUNGE_NOVA]:[spots[station]];",
"    let base=0;",
"    for(const list of lists){",
"      if(list&&slot-base<list.length&&slot-base>=0)return{x:list[slot-base][0],y:list[slot-base][1],upstairs:floor==='upstairs'};",
"      base+=(list||[]).length;",
"    }",
"  }",
"  return null;",
"}",
"function slotLogNearest(station,free,fromStation,fromSlot){",
"  const start=slotLogPoint(fromStation,fromSlot);",
"  if(!start||!free.length)return free[0];",
"  let best=null;",
"  for(const slot of free){",
"    const point=slotLogPoint(station,slot);",
"    if(!point)continue;",
"    const gap=Math.hypot(point.x-start.x,point.y-start.y)+(point.upstairs!==start.upstairs?SLOT_FLOOR_PENALTY:0);",
"    if(!best||gap<best.gap)best={slot,gap};",
"  }",
"  return best?best.slot:free[0];",
"}",
"function slotLogScores(rows){",
"  return SLOT_RULES_UNDER_TEST.map(rule=>{",
"    const per={};let hit=0;",
"    for(const row of rows){",
"      const right=rule.pick(row)===row.landed;",
"      if(right)hit++;",
"      const bucket=per[row.station]||(per[row.station]={hit:0,n:0});",
"      bucket.n++;if(right)bucket.hit++;",
"    }",
"    return{...rule,hit,n:rows.length,per};",
"  }).sort((a,b)=>b.hit-a.hit);",
"}",
"",
"// ─── Slot Lab ─"]));

// ── carry origin and target through the plan so a step can be logged ────────
sub("    steps.push({...describe(action,unit,from),unit,at:here??from,visit,assumed:Boolean(action.assumed)});",
J([ "    // The log needs to know where this droid started and which station it is",
    "    // heading for; describe() only produces prose.",
    "    steps.push({...describe(action,unit,from),unit,at:here??from,visit,assumed:Boolean(action.assumed),",
    "      kind:action.kind,from,fromSlot:startSlotAt.get(tracked[action.i]),to:action.to});"]));

fs.writeFileSync(APP,s,'utf8');
console.log('store, scoring and step metadata added');
